Set up PostgreSQL database and connection string
wes-harris/Deathflix-and-Chill pull request #1
Opened 2024-11-16 06:26 UTC by WesleyHarris

2024-11-16 06:30 UTC, matthewjenner requested changes

2024-11-16 06:30 UTC, matthewjenner commented on README.md
> +// Hi, Matt!
No....

2024-11-16 06:31 UTC, WesleyHarris commented on README.md
> +// Hi, Matt!
Why not?

2024-11-16 22:56 UTC, matthewjenner commented
Looks like you are missing a .gitignore file, so you are checking in secrets (.env file) as well as binaries (obj/ and bin/ folders)

Ask Claude to generate you a .gitignore file for a react project with a .net core api backend and how to fix your branch on the remote if you checked in some files that should have been caught by the ignore file.

2024-11-17 01:50 UTC, WesleyHarris commented
Thanks, bro. Appreciate you looking at that. I knew that shouldn't have been in there but skipped a step when I got trapped in pgAdmin hell.

2024-11-17 02:08 UTC, matthewjenner approved these changes

2024-11-17 02:08 UTC, merged